### ISSUE TITLE
QuickMenu won't switch to XESS, stays at FSR 2.1.2

### ISSUE THREAD

**Issue by nokodemus** [optiscaler/OptiScaler#787]
Hi Guys, 

first of all thanks for all your efforts. Recently i discovered, that, using DLSS Inputs, quickmenu ingame won't switch and stay at XESS any more. it falls back to FSR 2.1.2 ... i tried Witcher 3 DX12 and Cyberpunk 2077 so far --> same issue, so it doesn't seem Game-related ...

Optiscaler version is latest stable
Installation: automatic
Hardware: Intel Arc B580
Window Mode: windowed borderless

what i already tried: 
- older optiscaler versions (0.7.8, 0.7.7 pre9)
- fresh and clean install of Intel Arc Drivers incl. reverting to 2 previous whql versions (8247, 8132)
- different variants at step 1 of automated install

there definitely was a time months ago, when it worked like a charm, quickmenu flawlessly switched to and stayed at XESS, also using DLSS Inputs.
But for now no chance any ore, overlay also shows me DLSS --> FSR 2.1.2, no matter how often i try to switch to XESS in Quickmenu

I'd appreciate any ideas for resolving this issue, thank you very much and please tell me if there's further info needed

**Comment by TheRazerMD** [comment]
No log, no game folder screenshot, not even using the Issue template as required.

Don't know if this is some ARC specific issue, but try the latest 0.9 build anyway. 

https://github.com/optiscaler/OptiScaler/actions/runs/19973046936

**Comment by nokodemus** [comment]
first of all thank you ...
unfortunately i can't find optiscaler.log inside game folder ... 
on remove_optiscaler.bat it also states, that optiscaler.log can't be found ... 

are there special prerequisites to automatically generate the Log?
i'll provide folder screenshot later, unfortunately i have no clue what to do with 0.9 build you provided, i don't know how to build that myself ....

edit: found it in quickmenu

**Comment by nokodemus** [comment]
Got it, here's the log ... please tell me if i need to provide another log level ... 

[14:34:28.434985] [I] NVSDK_NGX_D3D12_EvaluateFeature changeBackend is true, counter: 1
[14:34:28.435038] [I] NVSDK_NGX_D3D12_EvaluateFeature changing backend to xess
[14:34:29.443477] [I] NVSDK_NGX_D3D12_EvaluateFeature changeBackend is true, counter: 2
[14:34:29.443544] [I] NVSDK_NGX_D3D12_EvaluateFeature creating new XeSS feature
[14:34:29.443560] [I] IFeature::SetHandle Handle: 1000000
[14:34:29.443574] [I] IFeature::SetInitParameters Init Flag AutoExposure: true
[14:34:29.443586] [I] IFeature::SetInitParameters Init Flag DepthInverted: true
[14:34:29.443597] [I] IFeature::SetInitParameters Init Flag IsHdr: true
[14:34:29.443608] [I] IFeature::SetInitParameters Init Flag JitteredMV: false
[14:34:29.443618] [I] IFeature::SetInitParameters Init Flag LowResMV: true
[14:34:29.443629] [I] IFeature::SetInitParameters Init Flag SharpenEnabled: false
[14:34:29.443644] [I] IFeature::SetInitParameters Render Resolution: 1706x960, Display Resolution 2560x1440, Quality: 2
[14:34:29.449733] [I] NVSDK_NGX_D3D12_EvaluateFeature changeBackend is true, counter: 3
[14:34:29.474893] [E] XeSSFeature::InitXeSS xessD3D12CreateContext error: Unsupported Driver
[14:34:29.474931] [E] NVSDK_NGX_D3D12_EvaluateFeature init failed with xess feature
[14:34:29.479492] [I] NVSDK_NGX_D3D12_EvaluateFeature changeBackend is true, counter: 1
[14:34:29.479551] [I] NVSDK_NGX_D3D12_EvaluateFeature changing backend to fsr21
[14:34:30.484412] [I] NVSDK_NGX_D3D12_EvaluateFeature changeBackend is true, counter: 2
[14:34:30.484474] [I] NVSDK_NGX_D3D12_EvaluateFeature creating new FSR 2.1.2 feature
[14:34:30.484498] [I] IFeature::SetHandle Handle: 1000000
[14:34:30.484515] [I] IFeature::SetInitParameters Init Flag AutoExposure: true
[14:34:30.484533] [I] IFeature::SetInitParameters Init Flag DepthInverted: true
[14:34:30.484544] [I] IFeature::SetInitParameters Init Flag IsHdr: true
[14:34:30.484556] [I] IFeature::SetInitParameters Init Flag JitteredMV: false
[14:34:30.484567] [I] IFeature::SetInitParameters Init Flag LowResMV: true
[14:34:30.484578] [I] IFeature::SetInitParameters Init Flag SharpenEnabled: false
[14:34:30.484594] [I] IFeature::SetInitParameters Render Resolution: 1706x960, Display Resolution 2560x1440, Quality: 2
[14:34:30.490756] [I] NVSDK_NGX_D3D12_EvaluateFeature changeBackend is true, counter: 3
[14:34:30.511886] [I] NVSDK_NGX_D3D12_EvaluateFeature init successful for fsr21, upscaler changed

**Comment by TheRazerMD** [comment]
1. The 0.9 link I've sent you is an already compiled build, all you have to do is download the zip at the bottom of the page (under Artifacts) and install Opti as usual.
2. The required Crash/Bug template explains how to create a log and which log level. And for future reference, please don't send an excerpt from the log, upload the entire log file as it may have more crucial info.

> _OptiScaler.log _(set `LogLevel=0` and `LogToFile=true` in OptiScaler.ini, zip it if too big)__

3. Also, `[E] XeSSFeature::InitXeSS xessD3D12CreateContext error: Unsupported Driver` implies something is either wrong with the driver, or Intel broke OptiScaler again if you're using the latest Arc driver (as they did previously and fixed in next driver). 

Please recheck this with the 0.9 build as 0.7 builds are EOL. Maybe even try DDU-ing the driver and reinstalling again if still not working. Our Arc testers haven't noticed any of these issues yet, but I'll go check with them.

**Comment by nokodemus** [comment]
First of all, thank you very much for looking into this and your hints.

I uninstalled the drivers in safe mode using DDU. After a normal reboot i installed the latest ARC Display Driver (8331) and installed the 0.9 build of optiscaler using automated install. Unfortunately the issue persists ... I'll attach the trace level log.

Thank you very much.

[optiscaler.zip](https://github.com/user-attachments/files/24053934/optiscaler.zip)

**Comment by TheRazerMD** [comment]
```
[E] XeSSFeature::InitXeSS xessD3D12CreateContext error: Unsupported Driver
[E] FeatureProvider_Dx12::ChangeFeature init failed with xess feature
```

Still the same error which we can't reproduce nor can our Arc testers. Are you using some old cracked version of the game or what? If GOG version, then maybe try `DisableOverlays=true` in Optiscaler.ini or kill GOG Galaxy.

**Comment by nokodemus** [comment]
I see ... i think i'll go with my plan B and image an old backup image ... 
yeah it's GOG Version but i also have exactly same issue with other games, e.g. Cyberpunk 2077, Horizon series or a Plague Tale series ... all legit copies ...
and just as stated before, there was a time months ago when it worked flawlessly, so i guess there's something going on regarding my system that shouldn't ... 

first i'll try your hint regarding DisableOverlays but as obviously nobody can recreate this, i think i'll go with a fresh start using my backup image. I'll check back wether a fresh windows resolved the issue ... 

Thank you anyway

**Comment by nokodemus** [comment]
Hi there ... as promised i'd like to check back ...

The issue resolved itself after imaging my backup image. Latest Intel ARC driver in combination with optiscaler v 0.9.0 pre6 works like a charm ... i only tested The Witcher 3 so far but i'd bet that it's also resolved regarding the other games ...

i have no idea what exactly was wrong on my system, but however a fresh start helped ... i think the issue can be closed 

Thank you very much for guiding me through

**Comment by TheRazerMD** [comment]
Happy to hear it's been successfully resolved 🎉
